### ISSUE TITLE
一万个👍

### ISSUE THREAD

**Issue by boholder** [oxyethylene/nacos-jasypt-plugin#1]
落泪啊，全github只搜到您真的实现了除了“base64加密”（乐）以外的配置加密插件，感谢！

https://github.com/search?q=%22com.alibaba.nacos.plugin.environment.spi.CustomEnvironmentPluginService%22&type=code

**Comment by oxyethylene** [comment]
很高兴可以帮到你。如果你有其他的建议欢迎继续提issue
